version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    network_mode: host
    command: sh -c "knex migrate:latest --knexfile src/infra/db/adapters/knex/knexfile.js && knex seed:run --knexfile src/infra/db/adapters/knex/knexfile.js && yarn start"
    environment:
      - POSTGRES_DB=ms_projects
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5435
      - POSTGRES_HOST=localhost
      - NODE_ENV=development
      - PORT=3002
    deploy:
       restart_policy:
        condition: on-failure
        max_attempts: 5
    depends_on: 
      - postgres
    volumes:
      - .:/usr/app
      
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=ms_projects
      - POSTGRES_HOST=localhost
    user: postgres
    volumes:
      - database:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    network_mode: host
    restart: always
    command: -p 5435
    
volumes:
  database:
